version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1234"
      ACCEPT_EULA: "Y"
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
    driver: local